import type { Theory } from './lessonTheory';

export const b2TheoryRu: Theory[] = [
  { goal:'Связывать события с помощью Future Perfect и Future Perfect Continuous.', explanation:['Future Perfect показывает результат, который будет готов к моменту в будущем. Future Perfect Continuous подчёркивает длительность процесса до этого момента.','Сравни результат “will have completed” и длительность “will have been working”.'], formula:'will have + V3 · will have been + verb-ing', examples:[{english:'By June, I will have finished the course.',translation:'К июню я закончу курс.'},{english:'By noon, she will have been working for six hours.',translation:'К полудню она будет работать уже шесть часов.'}], mistake:'После will have используй третью форму глагола, а не Past Simple.', tip:'Спроси: важен готовый результат или длительность процесса?' },
  { goal:'Выбирать Passive Voice и causative have, когда исполнитель не главный.', explanation:['Passive Voice переносит внимание с исполнителя на действие или результат. Causative have показывает, что работу для нас выполняет другой человек.','Исполнитель добавляется с by только тогда, когда он действительно важен.'], formula:'be + V3 · have + object + V3', examples:[{english:'The bridge will be completed next year.',translation:'Мост завершат в следующем году.'},{english:'I had my phone repaired.',translation:'Мне отремонтировали телефон.'}], mistake:'Не забывай изменять be по времени: is made, was made, has been made.', tip:'Если важен объект или результат, попробуй passive; если заказал услугу — causative have.' },
  { goal:'Точно передавать чужую речь, вопросы и просьбы.', explanation:['В reported speech местоимения, время и указатели времени меняются относительно новой ситуации. В косвенном вопросе порядок слов становится утвердительным.','Для просьб и приказов используй told/asked + object + to-infinitive.'], formula:'said (that) + clause · asked + if/question word + subject + verb · told + object + to verb', examples:[{english:'She said that she was tired.',translation:'Она сказала, что устала.'},{english:'He asked me where I lived.',translation:'Он спросил, где я живу.'}], mistake:'В косвенном вопросе не используй обратный порядок: “where I lived”, не “where did I live”.', tip:'Сначала определи говорящего, слушателя и момент речи, затем меняй формы.' },
  { goal:'Выражать условия точно: mixed conditionals, inversion и формальные связки.', explanation:['Mixed conditionals связывают причину в одном времени с результатом в другом. Инверсия Had I known заменяет If I had known в более формальном стиле.','Provided that, as long as и unless уточняют условие и помогают избежать повторов if.'], formula:'If + Past Perfect, would + verb now · Had + subject + V3, would have + V3', examples:[{english:'If I had studied medicine, I would be a doctor now.',translation:'Если бы я изучал медицину, сейчас был бы врачом.'},{english:'Had I known, I would have acted differently.',translation:'Если бы я знал, я поступил бы иначе.'}], mistake:'Не ставь would в if-части обычного условного предложения.', tip:'Нарисуй две точки: время причины и время результата.' },
  { goal:'Делать выводы и оценивать прошлые действия с past modals.', explanation:['Must have выражает сильную уверенность, might/could have — возможность, can’t have — уверенность, что этого не было.','Should have оценивает прошлое действие как ошибку или упущенную возможность.'], formula:'modal + have + V3', examples:[{english:'She must have missed the bus.',translation:'Должно быть, она пропустила автобус.'},{english:'You should have told me earlier.',translation:'Тебе следовало сказать мне раньше.'}], mistake:'После modal + have нужна третья форма: “must have gone”, не “must have went”.', tip:'Определи функцию: вывод, возможность, критика или сожаление.' },
  { goal:'Выбирать gerund или infinitive и использовать естественные сочетания слов.', explanation:['Некоторые глаголы требуют -ing, другие — to-infinitive. У remember, stop и try выбор формы меняет смысл.','На B2 важно учить не отдельные слова, а сочетания: raise awareness, reach a conclusion, highly effective.'], formula:'verb + -ing / to + verb · adjective + noun · verb + noun', examples:[{english:'I remember meeting her.',translation:'Я помню, как встретил её.'},{english:'We need to raise awareness.',translation:'Нам нужно повысить осведомлённость.'}], mistake:'Не выбирай форму по переводу: проверь модель конкретного английского глагола.', tip:'Записывай новое слово вместе с двумя типичными партнёрами.' },
  { goal:'Строить сложный, но ясный текст с инверсией, причастными оборотами и связками.', explanation:['Инверсия после negative adverbials добавляет формальный акцент: Rarely have I seen. Причастные обороты сокращают придаточные, если исполнитель понятен.','Связки nevertheless, whereas, consequently и in addition показывают точное отношение между идеями.'], formula:'Negative adverbial + auxiliary + subject · participle clause, main clause', examples:[{english:'Rarely have I heard such a clear argument.',translation:'Редко я слышал такой ясный аргумент.'},{english:'Having finished the report, she sent it.',translation:'Закончив отчёт, она отправила его.'}], mistake:'Причастный оборот и главное предложение должны относиться к одному исполнителю.', tip:'После написания проверь каждую связку: она действительно показывает нужное отношение?' },
];

export const b2TheoryKz: Theory[] = [
  {goal:'Future Perfect және Future Perfect Continuous арқылы оқиғаларды байланыстыру.',explanation:['Future Perfect болашақтағы белгілі сәтке дайын болатын нәтижені көрсетеді. Future Perfect Continuous сол сәтке дейінгі үдерістің ұзақтығын көрсетеді.','“Will have completed” — нәтиже, “will have been working” — ұзақтық.'],formula:'will have + V3 · will have been + verb-ing',examples:[{english:'By June, I will have finished the course.',translation:'Маусымға дейін курсты аяқтаймын.'},{english:'By noon, she will have been working for six hours.',translation:'Түске дейін оның жұмыс істегеніне алты сағат болады.'}],mistake:'Will have сөзінен кейін Past Simple емес, етістіктің үшінші формасын қолдан.',tip:'Дайын нәтиже маңызды ма, әлде үдерістің ұзақтығы ма?'},
  {goal:'Орындаушы маңызды болмағанда Passive Voice және causative have қолдану.',explanation:['Passive Voice назарды орындаушыдан әрекетке немесе нәтижеге аударады. Causative have жұмысты басқа адамның біз үшін орындағанын көрсетеді.','By + орындаушы тек ол шынымен маңызды болса қосылады.'],formula:'be + V3 · have + object + V3',examples:[{english:'The bridge will be completed next year.',translation:'Көпір келесі жылы аяқталады.'},{english:'I had my phone repaired.',translation:'Мен телефонымды жөндеттім.'}],mistake:'Be формасын шаққа сай өзгерт: is made, was made, has been made.',tip:'Нәтиже маңызды болса passive, қызметке тапсырыс берсең causative have қолдан.'},
  {goal:'Басқа адамның сөзін, сұрағын және өтінішін дәл жеткізу.',explanation:['Reported speech ішінде есімдіктер, шақ және уақыт көрсеткіштері жаңа жағдайға сай өзгереді. Жанама сұрақта сөз тәртібі жай сөйлемдегідей болады.','Өтініш пен бұйрық үшін told/asked + object + to-infinitive қолдан.'],formula:'said (that) + clause · asked + if/question word + subject + verb',examples:[{english:'She said that she was tired.',translation:'Ол шаршағанын айтты.'},{english:'He asked me where I lived.',translation:'Ол менің қайда тұратынымды сұрады.'}],mistake:'Жанама сұрақта “where did I live” емес, “where I lived” де.',tip:'Алдымен кім, кімге және қашан айтқанын анықта.'},
  {goal:'Mixed conditionals, inversion және формалды жалғаулықтармен шартты нақты білдіру.',explanation:['Mixed conditionals бір уақыттағы себепті басқа уақыттағы нәтижемен байланыстырады. Had I known — If I had known құрылымының формалды түрі.','Provided that, as long as және unless шарттың мағынасын нақтылайды.'],formula:'If + Past Perfect, would + verb now · Had + subject + V3, would have + V3',examples:[{english:'If I had studied medicine, I would be a doctor now.',translation:'Медицинаны оқығанымда, қазір дәрігер болар едім.'},{english:'Had I known, I would have acted differently.',translation:'Білгенімде, басқаша әрекет етер едім.'}],mistake:'Кәдімгі шартты сөйлемнің if-бөлігіне would қойма.',tip:'Себеп пен нәтиженің уақытын бөлек белгіле.'},
  {goal:'Past modals арқылы қорытынды жасау және өткен әрекетті бағалау.',explanation:['Must have — жоғары сенімділік, might/could have — мүмкіндік, can’t have — болмағанына сенімділік.','Should have өткен қателікті немесе жіберілген мүмкіндікті бағалайды.'],formula:'modal + have + V3',examples:[{english:'She must have missed the bus.',translation:'Ол автобусты өткізіп алған болуы керек.'},{english:'You should have told me earlier.',translation:'Маған ертерек айтуың керек еді.'}],mistake:'Modal + have сөздерінен кейін үшінші форма керек: “must have gone”.',tip:'Мағынаны анықта: қорытынды, мүмкіндік, сын немесе өкініш.'},
  {goal:'Gerund пен infinitive таңдап, табиғи сөз тіркестерін қолдану.',explanation:['Кей етістіктер -ing, басқалары to-infinitive талап етеді. Remember, stop және try сөздерінде форма мағынаны өзгертеді.','B2-де жеке сөз емес, raise awareness сияқты тіркестерді үйрену маңызды.'],formula:'verb + -ing / to + verb · adjective + noun · verb + noun',examples:[{english:'I remember meeting her.',translation:'Онымен кездескенім есімде.'},{english:'We need to raise awareness.',translation:'Ақпараттандыруды арттыруымыз керек.'}],mistake:'Форманы аудармаға қарап таңдама; ағылшын етістігінің моделін тексер.',tip:'Жаңа сөзді екі жиі қолданылатын серігімен бірге жаз.'},
  {goal:'Инверсия, есімше орамы және байланыстырушылармен күрделі, анық мәтін құру.',explanation:['Negative adverbials кейінгі инверсия формалды екпін береді. Есімше орамы орындаушы түсінікті болса, бағыныңқы сөйлемді қысқартады.','Nevertheless, whereas, consequently және in addition идеялар арасындағы байланысты дәл көрсетеді.'],formula:'Negative adverbial + auxiliary + subject · participle clause, main clause',examples:[{english:'Rarely have I heard such a clear argument.',translation:'Мұндай анық дәлелді сирек естідім.'},{english:'Having finished the report, she sent it.',translation:'Есепті аяқтап, ол оны жіберді.'}],mistake:'Есімше орамы мен негізгі сөйлемнің орындаушысы бір адам болуы керек.',tip:'Мәтіндегі әр байланыстырушы сөздің қатынасты дұрыс көрсеткенін тексер.'},
];
