import type { Theory } from './lessonTheory';
import type { CourseLevel } from './courseData';

export const a1TheoryKz: Theory[] = [
  { goal: 'Өзіңді таныстырып, to be етістігімен сөйлем құру.', explanation: ['To be — «болу» деген мағынаны береді. Қазақ тілінде «Мен оқушымын» дейміз, ал ағылшын тілінде am сөзін міндетті түрде қолданамыз.', 'Форма бастауышқа байланысты: I сөзінен кейін am, he/she/it сөздерінен кейін is, you/we/they сөздерінен кейін are келеді.'], formula: 'I + am · He/She/It + is · You/We/They + are', examples: [{ english: 'I am Alex.', translation: 'Менің атым Алекс.' }, { english: 'She is my friend.', translation: 'Ол — менің досым.' }, { english: 'We are students.', translation: 'Біз оқушымыз.' }], mistake: '“I is” деуге немесе am сөзін тастап кетуге болмайды.', tip: 'Алдымен бастауышты тап, содан кейін am, is немесе are формасын таңда.' },
  { goal: 'Өзің, отбасың және өзіңде бар заттар туралы айту.', explanation: ['Have got — «бар» деген мағынаны білдіреді. I, you, we, they сөздерімен have got қолданылады.', 'He, she, it сөздерінен кейін has got келеді. Сұрақта have немесе has сөйлемнің басына шығады.'], formula: 'I/You/We/They + have got · He/She/It + has got', examples: [{ english: 'I have got a sister.', translation: 'Менің әпкем бар.' }, { english: 'He has got a bike.', translation: 'Оның велосипеді бар.' }, { english: 'Have you got a pet?', translation: 'Сенің үй жануарың бар ма?' }], mistake: 'He немесе she сөздерінен кейін have got емес, has got қолданылады.', tip: 'He, she және has сөздерін бір топ ретінде есте сақта.' },
  { goal: 'Күнделікті әдеттер мен кесте туралы айту.', explanation: ['Present Simple үнемі немесе жиі қайталанатын әрекеттерді сипаттайды.', 'He, she, it сөздерінен кейін етістікке көбіне -s жалғанады. Does бар сөйлемде негізгі етістікке -s жалғанбайды.'], formula: 'I/You/We/They + verb · He/She/It + verb-s', examples: [{ english: 'I study every day.', translation: 'Мен күн сайын оқимын.' }, { english: 'She plays tennis.', translation: 'Ол теннис ойнайды.' }, { english: 'Does he work?', translation: 'Ол жұмыс істей ме?' }], mistake: '“Does she plays?” емес, “Does she play?” деп айту керек.', tip: 'Every day, usually, often сөздері Present Simple-ды жиі көрсетеді.' },
  { goal: 'Үйді, қаланы және заттардың орнын сипаттау.', explanation: ['There is және there are белгілі бір жерде бір нәрсе бар екенін білдіреді.', 'Бір затпен there is, бірнеше затпен there are қолданылады.'], formula: 'There is + бір зат · There are + бірнеше зат', examples: [{ english: 'There is a book on the table.', translation: 'Үстелдің үстінде кітап бар.' }, { english: 'There are two parks here.', translation: 'Мұнда екі саябақ бар.' }, { english: 'Is there a shop nearby?', translation: 'Жақын жерде дүкен бар ма?' }], mistake: 'Бір затпен there are қолданба: “There is a house” дұрыс.', tip: 'Алдымен заттарды сана: біреу болса is, бірнешеу болса are.' },
  { goal: 'Тамақ, оның мөлшері және сауда туралы айту.', explanation: ['Some және any нақты емес мөлшерді білдіреді. Some көбіне жай сөйлемде, any сұрақ пен болымсыз сөйлемде қолданылады.', 'Саналатын заттарды жеке санауға болады, ал water, milk, bread сияқты сөздер саналмайды.'], formula: 'Жай сөйлем: some · Сұрақ/болымсыз сөйлем: any', examples: [{ english: 'I have some apples.', translation: 'Менде бірнеше алма бар.' }, { english: 'Do you have any water?', translation: 'Сенде су бар ма?' }, { english: 'We do not have any bread.', translation: 'Бізде нан жоқ.' }], mistake: '“A water” деме. “Some water” немесе “a bottle of water” де.', tip: 'Бір нәрсе бар болса — some, бар-жоғын сұрасақ — any.' },
  { goal: 'Дәл қазір болып жатқан әрекеттерді сипаттау.', explanation: ['Present Continuous сөйлеу сәтіндегі процесті көрсетеді. Ол to be формасы мен -ing жалғанған етістіктен құралады.', 'I play every day — әдет. I am playing now — әрекет дәл қазір болып жатыр.'], formula: 'am/is/are + verb-ing', examples: [{ english: 'I am reading now.', translation: 'Мен қазір кітап оқып отырмын.' }, { english: 'They are playing outside.', translation: 'Олар далада ойнап жүр.' }, { english: 'She is not sleeping.', translation: 'Ол қазір ұйықтап жатқан жоқ.' }], mistake: 'To be сөзін тастама: “I reading” емес, “I am reading”.', tip: 'Now және at the moment сөздері Present Continuous-ты көрсетеді.' },
  { goal: 'Өткен шақта аяқталған оқиғалар туралы айту.', explanation: ['Past Simple өткен шақта аяқталған әрекетке қолданылады. Көбіне yesterday, last week, ago сөздері кездеседі.', 'Дұрыс етістікке -ed жалғанады. Бұрыс етістіктердің формасын есте сақтау керек: go — went, see — saw.'], formula: 'Жай сөйлем: verb-ed / V2 · Болымсыз: did not + verb', examples: [{ english: 'I visited my friend yesterday.', translation: 'Мен кеше досыма бардым.' }, { english: 'We went to the park.', translation: 'Біз саябаққа бардық.' }, { english: 'She did not play.', translation: 'Ол ойнаған жоқ.' }], mistake: 'Did сөзінен кейін бастапқы форма келеді: “Did you go?”, “Did you went?” емес.', tip: 'Өткен уақытты тап, содан кейін етістіктің дұрыс не бұрыс екенін тексер.' },
];

export const a2TheoryKz: Theory[] = [
  { goal:'Артикльдер мен мөлшер сөздерін дұрыс қолдану.', explanation:['A және an белгісіз бір затты алғаш атағанда қолданылады: a book, an apple. The тыңдаушыға белгілі немесе бұрын аталған заттың алдында келеді.','Саналатын заттармен many, a few, few; саналмайтын заттармен much, a little, little қолданылады. Some мен any екі топпен де келе алады.'], formula:'a/an + жекеше зат · the + белгілі зат · many/much + зат есім', examples:[{english:'I saw a dog. The dog was friendly.',translation:'Мен бір ит көрдім. Әлгі ит жуас екен.'},{english:'We have a little time.',translation:'Біздің аздап уақытымыз бар.'}], mistake:'Жалпы көпше мағынада артикль қойма: “Cats are animals”, “The cats are animals” емес.', tip:'Өзіңнен сұра: зат біреу ме, саналатын ба және тыңдаушыға белгілі ме?' },
  { goal:'Present Simple мен Present Continuous шақтарын ажырату.', explanation:['Present Simple әдетті, кестені және тұрақты жағдайды білдіреді. Present Continuous дәл қазір немесе уақытша жүріп жатқан әрекетті көрсетеді.','Know, like, need сияқты күй етістіктері көбіне Continuous формасында қолданылмайды.'], formula:'Әдет: subject + V1/V-s · Қазір: subject + am/is/are + V-ing', examples:[{english:'I usually walk to school.',translation:'Мен мектепке әдетте жаяу барамын.'},{english:'Today I am taking the bus.',translation:'Бүгін автобуспен бара жатырмын.'}], mistake:'“I am knowing the answer” деме; дұрыс нұсқа — “I know the answer”.', tip:'Every day — әдет, now — қазіргі үдеріс. Бірақ ең алдымен сөйлемнің мағынасын түсін.' },
  { goal:'Past Simple мен Past Continuous арқылы өткен оқиғаны баяндау.', explanation:['Past Continuous өткен шақтағы ұзақ әрекетті немесе оқиғаның фонын көрсетеді. Past Simple сол кезде болған қысқа, аяқталған әрекетті білдіреді.','When көбіне негізгі оқиғаны, while қатар жүріп жатқан ұзақ әрекетті байланыстырады.'], formula:'Фон: was/were + V-ing · Оқиға: V2 / V-ed', examples:[{english:'I was walking home when it started to rain.',translation:'Үйге келе жатқанымда жаңбыр жауа бастады.'},{english:'While she was cooking, I set the table.',translation:'Ол тамақ әзірлеп жатқанда, мен дастарқан жайдым.'}], mistake:'Did сөзінен кейін V2 қолданба: “Did it start?”, “Did it started?” емес.', tip:'Оқиғаны сурет деп елестет: артқы көрініс — Continuous, болған оқиға — Simple.' },
  { goal:'Present Perfect пен Past Simple айырмасын түсіну.', explanation:['Present Perfect өткен әрекетті қазіргі нәтижесімен немесе өмірлік тәжірибемен байланыстырады. Нақты өткен уақыт айтылмайды.','Past Simple аяқталған өткен уақытпен қолданылады: yesterday, in 2024, last week.'], formula:'Present Perfect: have/has + V3 · Past Simple: V2/V-ed', examples:[{english:'I have lost my key, so I cannot open the door.',translation:'Кілтімді жоғалтып алдым, сондықтан есікті аша алмаймын.'},{english:'I lost my key yesterday.',translation:'Кеше кілтімді жоғалтып алдым.'}], mistake:'Нақты аяқталған уақытпен Present Perfect қолданба: “I saw him yesterday” дұрыс.', tip:'Қазіргі нәтиже маңызды ма? Perfect. Қашан болғаны маңызды ма? Past Simple.' },
  { goal:'Болашақ жоспар, шешім және болжамды дұрыс білдіру.', explanation:['Be going to алдын ала жоспарды немесе көзге көрінетін белгіге негізделген болжамды білдіреді. Will сөйлеу сәтіндегі шешім, уәде немесе жалпы болжам үшін қолданылады.','Present Continuous нақты келісілген жоспарға келеді: уақыт пен орын көбіне белгілі болады.'], formula:'will + V1 · am/is/are going to + V1 · am/is/are + V-ing', examples:[{english:'I am meeting Dana at six.',translation:'Мен Данамен сағат алтыда кездесемін.'},{english:'Look at those clouds. It is going to rain.',translation:'Ана бұлттарға қарашы. Жаңбыр жауғалы тұр.'}], mistake:'Will сөзінен кейін to қойма: “will go”, “will to go” емес.', tip:'Жоспар қашан жасалды және ол қаншалықты нақты екенін анықта.' },
  { goal:'Модаль етістіктер мен Zero және First Conditional қолдану.', explanation:['Can қабілетті, must міндетті, should кеңесті, might мүмкіндікті білдіреді. Модаль етістіктен кейін негізгі етістік бастапқы формада келеді.','Zero Conditional әрдайым дұрыс болатын нәтижені, First Conditional болашақтағы шынайы мүмкіндікті көрсетеді.'], formula:'modal + V1 · If + Present Simple, Present Simple / will + V1', examples:[{english:'If you heat ice, it melts.',translation:'Мұзды қыздырсаң, ол ериді.'},{english:'If it rains, we will stay home.',translation:'Жаңбыр жауса, үйде қаламыз.'}], mistake:'If-бөлігінде will қолданба: “If it rains”, “If it will rain” емес.', tip:'Бұл жалпы заңдылық па, әлде болашақтағы ықтимал жағдай ма — соны анықта.' },
  { goal:'Абзацтары мен жалғаулықтары бар түсінікті мәтін жазу.', explanation:['Әр абзац бір негізгі ойды дамытады: алдымен тақырыптық сөйлем, содан кейін түсіндіру мен мысал келеді.','First, however, because, therefore, finally сияқты жалғаулықтар ойлар арасындағы ретті, себепті немесе қарама-қарсылықты көрсетеді.'], formula:'Негізгі ой + түсіндіру + мысал · жалғаулық + келесі ой', examples:[{english:'I enjoy city life because everything is nearby.',translation:'Маған қала өмірі ұнайды, себебі бәрі жақын.'},{english:'However, cities can be noisy.',translation:'Алайда қалалар шулы болуы мүмкін.'}], mistake:'Бір абзацқа байланыссыз бірнеше ойды жинама.', tip:'Жазып болған соң әр абзацтың негізгі ойын бір сөйлеммен айтып көр.' },
];

export const b1TheoryKz: Theory[] = [
  { goal:'Narrative tenses арқылы оқиғалардың ретін анық баяндау.', explanation:['Past Simple негізгі оқиғаларды ретімен береді. Past Continuous оқиғаның фонын көрсетеді, ал Past Perfect басқа өткен әрекеттен бұрын болған істі білдіреді.','Осы үш шақты бірге қолданғанда тыңдаушы қай оқиғаның бұрын, қайсысының кейін болғанын түсінеді.'], formula:'Фон: was/were + V-ing · Негізгі оқиға: V2 · Бұрынғы оқиға: had + V3', examples:[{english:'I was walking home when I realised that I had lost my wallet.',translation:'Үйге келе жатып, әмиянымды жоғалтып алғанымды түсіндім.'},{english:'The film had started before we arrived.',translation:'Біз келгенше фильм басталып қойған еді.'}], mistake:'Барлық өткен әрекетті Past Simple-мен бере берме; олардың ретін анықта.', tip:'Алдымен уақыт сызығын сыз: ең бұрынғы әрекетке Past Perfect қолдан.' },
  { goal:'Perfect шақтары арқылы нәтиже мен ұзақтықты көрсету.', explanation:['Present Perfect қазіргі уақытпен байланысты нәтиже не тәжірибені білдіреді. Present Perfect Continuous әрекеттің қанша уақыт жүріп жатқанын ерекше көрсетеді.','Past Perfect өткендегі басқа сәтке дейін дайын болған нәтижені білдіреді.'], formula:'have/has + V3 · have/has been + V-ing · had + V3', examples:[{english:'I have finished the report.',translation:'Мен есепті аяқтап қойдым.'},{english:'I have been working for three hours.',translation:'Менің жұмыс істеп жатқаныма үш сағат болды.'}], mistake:'For — уақыт аралығы, since — басталған нүкте: for two years, since 2024.', tip:'Нәтиже маңызды болса Perfect, үдеріс пен ұзақтық маңызды болса Perfect Continuous таңда.' },
  { goal:'Passive Voice арқылы әрекет пен нәтижеге назар аудару.', explanation:['Passive Voice орындаушы белгісіз, маңызды емес немесе онсыз да түсінікті кезде қолданылады. Сөйлемнің назары әрекетке ұшыраған затқа ауысады.','Be етістігі шаққа сай өзгереді, ал негізгі етістік әрдайым V3 формасында тұрады.'], formula:'subject + be (шаққа сай) + V3 · by + орындаушы', examples:[{english:'The article was published yesterday.',translation:'Мақала кеше жарияланды.'},{english:'English is spoken in many countries.',translation:'Көптеген елде ағылшын тілінде сөйлейді.'}], mistake:'V3 алдында be формасын ұмытпа: “was built”, тек “built” емес.', tip:'Орындаушы емес, нәтиже маңызды болса, Passive Voice қолдан.' },
  { goal:'Reported Speech арқылы өзгенің сөзін жеткізу.', explanation:['Біреудің сөзін кейінірек жеткізгенде есімдіктер, уақыт көрсеткіштері және шақтар жаңа жағдайға сай өзгереді.','Жанама сұрақта сұраулы сөз тәртібі болмайды: subject етістіктің алдында тұрады.'], formula:'said (that) + clause · asked + if/question word + subject + verb', examples:[{english:'Mira said that she was tired.',translation:'Мира шаршағанын айтты.'},{english:'He asked where I lived.',translation:'Ол менің қайда тұратынымды сұрады.'}], mistake:'Жанама сұрақта “where did I live” емес, “where I lived” қолдан.', tip:'Кім айтты, қашан айтты және кім туралы айтты — осы үшеуін тексер.' },
  { goal:'Relative clauses арқылы зат пен адам туралы қосымша ақпарат беру.', explanation:['Who адамға, which затқа, where орынға қатысты қолданылады. That анықтаушы сөйлемде who немесе which орнына келе алады.','Non-defining clause тек қосымша ақпарат береді және үтірмен бөлінеді; онда that қолданылмайды.'], formula:'person + who/that · thing + which/that · place + where', examples:[{english:'The girl who won the prize is my friend.',translation:'Жүлде алған қыз — менің досым.'},{english:'Astana, which is the capital, is growing quickly.',translation:'Елорда болып саналатын Астана тез дамып келеді.'}], mistake:'Қажетті ақпаратты беретін defining clause алдына үтір қойма.', tip:'Ақпаратсыз қай адам не зат екені түсінікті ме? Түсінікті болса, үтір керек болуы мүмкін.' },
  { goal:'Second және Third Conditional арқылы болжам мен өкінішті білдіру.', explanation:['Second Conditional қазіргі немесе болашақтағы шындыққа сай емес, елестетілген жағдайды білдіреді. Third Conditional өткенде болмаған жағдай мен оның мүмкін нәтижесін көрсетеді.','Бұл құрылымдар кеңес, арман, сын және өкініш айтуға көмектеседі.'], formula:'If + Past Simple, would + V1 · If + Past Perfect, would have + V3', examples:[{english:'If I had more time, I would learn Spanish.',translation:'Уақытым көбірек болса, испан тілін үйренер едім.'},{english:'If we had left earlier, we would have caught the train.',translation:'Ертерек шыққанымызда, пойызға үлгерер едік.'}], mistake:'If-бөлігіне would қойма; Third Conditional ішінде had + V3 қолдан.', tip:'Second — қазір не болашақ, Third — өзгерте алмайтын өткен шақ.' },
  { goal:'Мәтіндегі автор пікірін, дәлелін және мысалын талдау.', explanation:['Автордың негізгі ойын табу үшін тақырыптық сөйлемдер мен қорытындыға назар аудар. Дәлел ойды негіздейді, ал мысал оны нақтылайды.','Opinion essay ішінде кіріспе, жүйелі дәлелдер, қарсы пікірге жауап және қорытынды болуы керек.'], formula:'Пікір + себеп + дәлел/мысал · қарсы пікір + жауап · қорытынды', examples:[{english:'In my view, schools should teach financial skills because students need them in real life.',translation:'Меніңше, мектептер қаржылық сауаттылықты үйретуі керек, себебі ол оқушыларға өмірде қажет.'},{english:'Although this may be costly, the long-term benefits are greater.',translation:'Бұл қымбат болуы мүмкін, алайда ұзақ мерзімді пайдасы көбірек.'}], mistake:'Пікірді дәлелсіз қалдырма және мәтінді бірдей сөздермен қайталай берме.', tip:'Әр абзацқа сұрақ қой: ол менің негізгі ойымды қалай дәлелдейді?' },
];

export const practiceTheoryKz: Theory[] = [
  { goal:'Ағылшын тіліндегі диалогты тыңдап, негізгі ақпаратты табу.', explanation:['Алдымен жағдайды анықта: кім сөйлеп тұр, қайда және не үшін? Екінші тыңдағанда есім, сан, уақыт және себеп сияқты нақты мәліметтерге назар аудар.','Әр сөзді аударуға тырыспа. Таныс тірек сөздер мен сөйлеушінің дауыс ырғағы жалпы мағынаны түсінуге көмектеседі.'], formula:'1-тыңдау: жалпы мағына · 2-тыңдау: нақты мәлімет · жауапты тексеру', examples:[{english:'Could I have two tickets for Friday?',translation:'Жұмаға екі билет алсам бола ма?'},{english:'The train leaves at half past six.',translation:'Пойыз алты жарымда жүреді.'}], mistake:'Бір түсініксіз сөзге тоқтап қалып, келесі ақпаратты өткізіп алма.', tip:'Сұрақтарды алдын ала оқып, тыңдау кезінде қажет сөздерді қысқаша жаз.' },
  { goal:'Оқиғаны тыңдап, өз сөзіңмен ретімен мазмұндау.', explanation:['Мазмұндауда барлық сөйлемді жаттау қажет емес. Кейіпкерді, орынды, мәселені, негізгі оқиғаларды және нәтижені белгіле.','First, then, after that, eventually сияқты сөздер оқиғаның ретін анық көрсетеді.'], formula:'Кім/қайда → мәселе → негізгі оқиғалар → нәтиже', examples:[{english:'At first, Amir felt nervous, but then he asked for help.',translation:'Алғашында Әмір қобалжыды, бірақ кейін көмек сұрады.'},{english:'Eventually, they found the right address.',translation:'Ақырында олар дұрыс мекенжайды тапты.'}], mistake:'Мәтінді сөзбе-сөз қайталауға немесе шақтарды себепсіз ауыстыруға тырыспа.', tip:'Алдымен төрт тірек сөз жаз, кейін соларға сүйеніп сөйле.' },
  { goal:'Шынайы жағдайда сұрақ қойып, мәселені ағылшынша шешу.', explanation:['Алдымен мақсатыңды сыпайы айт, кейін қажетті мәліметті сұра. Жауап түсініксіз болса, нақтылау сұрағын қолдан.','Could you repeat that? және What do you mean by…? сияқты тіркестер әңгімені тоқтатпай жалғастыруға көмектеседі.'], formula:'Сәлемдесу → мақсат → сұрақ → нақтылау → алғыс', examples:[{english:'Excuse me, could you tell me how to get to the station?',translation:'Кешіріңіз, вокзалға қалай баруға болатынын айта аласыз ба?'},{english:'Could you say that again more slowly?',translation:'Соны тағы да баяуырақ айта аласыз ба?' }], mistake:'Тек жеке сөздермен жауап берме; толық әрі сыпайы сөйлем құр.', tip:'Жағдайды рөл ретінде елестетіп, кемінде бір нақтылау сұрағын қой.' },
  { goal:'Өз пікіріңді айтып, оны себеп пен мысал арқылы дәлелдеу.', explanation:['Жақсы жауап пікірден басталады, кейін оның себебі мен нақты мысалы беріледі. Күрделі деңгейде қарсы пікірді де қысқаша атап өту пайдалы.','Because, for example, however, on the other hand тіркестері ойларды байланыстырады.'], formula:'Пікір → себеп → мысал → қысқа қорытынды', examples:[{english:'I prefer studying in a group because we can explain difficult ideas to each other.',translation:'Мен топпен оқуды ұнатамын, себебі күрделі ойларды бір-бірімізге түсіндіре аламыз.'},{english:'However, studying alone can be more peaceful.',translation:'Дегенмен жалғыз оқу тынышырақ болуы мүмкін.'}], mistake:'“I think so” деп тоқтама; неліктен олай ойлайтыныңды түсіндір.', tip:'Жауабыңды кемінде төрт байланысты сөйлеммен құрастыр.' },
  { goal:'Қорытынды ауызша жұмыста анық, байланысты және сенімді сөйлеу.', explanation:['Жауапты қысқа жоспармен баста: кіріспе, екі негізгі ой және қорытынды. Сөйлеу кезінде қате кетсе, тоқтамай өзіңді түзетіп жалғастыр.','Дауыс ырғағы, анық айтылым және байланыстырушы сөздер грамматика сияқты маңызды.'], formula:'Кіріспе → 1-ой + мысал → 2-ой + мысал → қорытынды', examples:[{english:'Today I would like to talk about a skill I want to learn.',translation:'Бүгін мен үйренгім келетін бір дағды туралы айтқым келеді.'},{english:'To sum up, this skill would help me become more independent.',translation:'Қорытындылай келе, бұл дағды маған дербес болуға көмектесер еді.'}], mistake:'Жатталған мәтінді тым жылдам айтпа және сұрақтан ауытқыма.', tip:'Сөйлеу алдында 20 секунд ішінде төрт тірек сөзден жоспар құр.' },
];

export const defaultTheoryKz: Record<CourseLevel, Theory> = {
  A1: a1TheoryKz[0],
  A2: { goal: 'Ағылшын шақтарының айырмашылығын түсініп, оларды мәтінде дұрыс қолдану.', explanation: ['Ағылшын тілінде шақ әрекеттің уақытын ғана емес, оның мағынасын да көрсетеді: әдет, процесс, нәтиже немесе аяқталған оқиға.', 'Алдымен әрекеттің қашан болғанын анықта. Содан кейін оның ұзақтығын және қазіргі уақытпен байланысын тексер.'], formula: 'Әрекет уақыты + әрекет мағынасы → етістіктің дұрыс формасы', examples: [{ english: 'I work every day.', translation: 'Мен күн сайын жұмыс істеймін.' }, { english: 'I am working now.', translation: 'Мен қазір жұмыс істеп жатырмын.' }], mistake: 'Шақты бір ғана көмекші сөзге қарап таңдама. Сөйлемді толық оқы.', tip: 'Қысқа уақыт сызығын елестет: өткен шақ — қазіргі шақ — келер шақ.' },
  B1: { goal: 'Күрделі грамматиканы байланысты сөйлеуде сенімді қолдану.', explanation: ['B1 деңгейінде оқиғалар бір-бірімен байланысады: бір әрекет екіншісінен бұрын болды немесе өткен оқиға қазіргі уақытқа әсер етеді.', 'Грамматикалық формамен бірге сөйлеушінің не айтқысы келгенін түсіну маңызды.'], formula: 'Контекст + оқиғалар реті + нәтиже', examples: [{ english: 'I have already finished.', translation: 'Мен аяқтап қойдым.' }, { english: 'If I had time, I would travel.', translation: 'Уақытым болса, саяхаттар едім.' }], mistake: 'Ағылшын құрылымын қазақ тілінен сөзбе-сөз аударма.', tip: 'Жауап бермес бұрын бұл шақтың неге таңдалғанын өз сөзіңмен түсіндір.' },
  B2: { goal: 'Күрделі ойларды ағылшын тілінде табиғи, нақты және орынды жеткізу.', explanation: ['B2 деңгейінде бір ойды бірнеше тәсілмен айтуға болады. Таңдау контекстке, стильге және маңызды мағынаға байланысты.', 'Біз құрылымдарды салыстырып, сөйлемдерді басқаша құрып, мағына реңктерін байқаймыз.'], formula: 'Мағына + стиль + контекст → табиғи құрылым', examples: [{ english: 'The project has been completed.', translation: 'Жоба аяқталды.' }, { english: 'She said that she was ready.', translation: 'Ол дайын екенін айтты.' }], mistake: 'Күрделі форма әрқашан жақсы емес. Ең табиғи нұсқаны таңда.', tip: 'Сөйлемді толық оқып, оның нақты өмірдегі жағдайын елестет.' },
};
