import type { Theory } from './lessonTheory';
import type { CourseLevel } from './courseData';

export const a1TheoryKz: Theory[] = [
  { goal: 'Өзіңді таныстырып, to be етістігімен сөйлем құру.', explanation: ['To be — «болу» деген мағынаны береді. Қазақ тілінде «Мен оқушымын» дейміз, ал ағылшын тілінде am сөзін міндетті түрде қолданамыз.', 'Форма бастауышқа байланысты: I сөзінен кейін am, he/she/it сөздерінен кейін is, you/we/they сөздерінен кейін are келеді.'], formula: 'I + am · He/She/It + is · You/We/They + are', examples: [{ english: 'I am Alex.', translation: 'Менің атым Алекс.' }, { english: 'She is my friend.', translation: 'Ол — менің досым.' }, { english: 'We are students.', translation: 'Біз оқушымыз.' }], mistake: '“I is” деуге немесе am сөзін тастап кетуге болмайды.', tip: 'Алдымен бастауышты тап, содан кейін am, is немесе are формасын таңда.' },
  { goal: 'Өзің, отбасың және өзіңде бар заттар туралы айту.', explanation: ['Have got — «бар» деген мағынаны білдіреді. I, you, we, they сөздерімен have got қолданылады.', 'He, she, it сөздерінен кейін has got келеді. Сұрақта have немесе has сөйлемнің басына шығады.'], formula: 'I/You/We/They + have got · He/She/It + has got', examples: [{ english: 'I have got a sister.', translation: 'Менің әпкем бар.' }, { english: 'He has got a bike.', translation: 'Оның велосипеді бар.' }, { english: 'Have you got a pet?', translation: 'Сенің үй жануарың бар ма?' }], mistake: 'He немесе she сөздерінен кейін have got емес, has got қолданылады.', tip: 'He, she және has сөздерін бір топ ретінде есте сақта.' },
  { goal: 'Күнделікті әдеттер мен кесте туралы айту.', explanation: ['Present Simple үнемі немесе жиі қайталанатын әрекеттерді сипаттайды.', 'He, she, it сөздерінен кейін етістікке көбіне -s жалғанады. Does бар сөйлемде негізгі етістікке -s жалғанбайды.'], formula: 'I/You/We/They + verb · He/She/It + verb-s', examples: [{ english: 'I study every day.', translation: 'Мен күн сайын оқимын.' }, { english: 'She plays tennis.', translation: 'Ол теннис ойнайды.' }, { english: 'Does he work?', translation: 'Ол жұмыс істей ме?' }], mistake: '“Does she plays?” емес, “Does she play?” деп айту керек.', tip: 'Every day, usually, often сөздері Present Simple-ды жиі көрсетеді.' },
  { goal: 'Үйді, қаланы және заттардың орнын сипаттау.', explanation: ['There is және there are белгілі бір жерде бір нәрсе бар екенін білдіреді.', 'Бір затпен there is, бірнеше затпен there are қолданылады.'], formula: 'There is + бір зат · There are + бірнеше зат', examples: [{ english: 'There is a book on the table.', translation: 'Үстелдің үстінде кітап бар.' }, { english: 'There are two parks here.', translation: 'Мұнда екі саябақ бар.' }, { english: 'Is there a shop nearby?', translation: 'Жақын жерде дүкен бар ма?' }], mistake: 'Бір затпен there are қолданба: “There is a house” дұрыс.', tip: 'Алдымен заттарды сана: біреу болса is, бірнешеу болса are.' },
  { goal: 'Тамақ, оның мөлшері және сауда туралы айту.', explanation: ['Some және any нақты емес мөлшерді білдіреді. Some көбіне жай сөйлемде, any сұрақ пен болымсыз сөйлемде қолданылады.', 'Саналатын заттарды жеке санауға болады, ал water, milk, bread сияқты сөздер саналмайды.'], formula: 'Жай сөйлем: some · Сұрақ/болымсыз сөйлем: any', examples: [{ english: 'I have some apples.', translation: 'Менде бірнеше алма бар.' }, { english: 'Do you have any water?', translation: 'Сенде су бар ма?' }, { english: 'We do not have any bread.', translation: 'Бізде нан жоқ.' }], mistake: '“A water” деме. “Some water” немесе “a bottle of water” де.', tip: 'Бір нәрсе бар болса — some, бар-жоғын сұрасақ — any.' },
  { goal: 'Дәл қазір болып жатқан әрекеттерді сипаттау.', explanation: ['Present Continuous сөйлеу сәтіндегі процесті көрсетеді. Ол to be формасы мен -ing жалғанған етістіктен құралады.', 'I play every day — әдет. I am playing now — әрекет дәл қазір болып жатыр.'], formula: 'am/is/are + verb-ing', examples: [{ english: 'I am reading now.', translation: 'Мен қазір кітап оқып отырмын.' }, { english: 'They are playing outside.', translation: 'Олар далада ойнап жүр.' }, { english: 'She is not sleeping.', translation: 'Ол қазір ұйықтап жатқан жоқ.' }], mistake: 'To be сөзін тастама: “I reading” емес, “I am reading”.', tip: 'Now және at the moment сөздері Present Continuous-ты көрсетеді.' },
  { goal: 'Өткен шақта аяқталған оқиғалар туралы айту.', explanation: ['Past Simple өткен шақта аяқталған әрекетке қолданылады. Көбіне yesterday, last week, ago сөздері кездеседі.', 'Дұрыс етістікке -ed жалғанады. Бұрыс етістіктердің формасын есте сақтау керек: go — went, see — saw.'], formula: 'Жай сөйлем: verb-ed / V2 · Болымсыз: did not + verb', examples: [{ english: 'I visited my friend yesterday.', translation: 'Мен кеше досыма бардым.' }, { english: 'We went to the park.', translation: 'Біз саябаққа бардық.' }, { english: 'She did not play.', translation: 'Ол ойнаған жоқ.' }], mistake: 'Did сөзінен кейін бастапқы форма келеді: “Did you go?”, “Did you went?” емес.', tip: 'Өткен уақытты тап, содан кейін етістіктің дұрыс не бұрыс екенін тексер.' },
];

export const defaultTheoryKz: Record<CourseLevel, Theory> = {
  A1: a1TheoryKz[0],
  A2: { goal: 'Ағылшын шақтарының айырмашылығын түсініп, оларды мәтінде дұрыс қолдану.', explanation: ['Ағылшын тілінде шақ әрекеттің уақытын ғана емес, оның мағынасын да көрсетеді: әдет, процесс, нәтиже немесе аяқталған оқиға.', 'Алдымен әрекеттің қашан болғанын анықта. Содан кейін оның ұзақтығын және қазіргі уақытпен байланысын тексер.'], formula: 'Әрекет уақыты + әрекет мағынасы → етістіктің дұрыс формасы', examples: [{ english: 'I work every day.', translation: 'Мен күн сайын жұмыс істеймін.' }, { english: 'I am working now.', translation: 'Мен қазір жұмыс істеп жатырмын.' }], mistake: 'Шақты бір ғана көмекші сөзге қарап таңдама. Сөйлемді толық оқы.', tip: 'Қысқа уақыт сызығын елестет: өткен шақ — қазіргі шақ — келер шақ.' },
  B1: { goal: 'Күрделі грамматиканы байланысты сөйлеуде сенімді қолдану.', explanation: ['B1 деңгейінде оқиғалар бір-бірімен байланысады: бір әрекет екіншісінен бұрын болды немесе өткен оқиға қазіргі уақытқа әсер етеді.', 'Грамматикалық формамен бірге сөйлеушінің не айтқысы келгенін түсіну маңызды.'], formula: 'Контекст + оқиғалар реті + нәтиже', examples: [{ english: 'I have already finished.', translation: 'Мен аяқтап қойдым.' }, { english: 'If I had time, I would travel.', translation: 'Уақытым болса, саяхаттар едім.' }], mistake: 'Ағылшын құрылымын қазақ тілінен сөзбе-сөз аударма.', tip: 'Жауап бермес бұрын бұл шақтың неге таңдалғанын өз сөзіңмен түсіндір.' },
  B2: { goal: 'Күрделі ойларды ағылшын тілінде табиғи, нақты және орынды жеткізу.', explanation: ['B2 деңгейінде бір ойды бірнеше тәсілмен айтуға болады. Таңдау контекстке, стильге және маңызды мағынаға байланысты.', 'Біз құрылымдарды салыстырып, сөйлемдерді басқаша құрып, мағына реңктерін байқаймыз.'], formula: 'Мағына + стиль + контекст → табиғи құрылым', examples: [{ english: 'The project has been completed.', translation: 'Жоба аяқталды.' }, { english: 'She said that she was ready.', translation: 'Ол дайын екенін айтты.' }], mistake: 'Күрделі форма әрқашан жақсы емес. Ең табиғи нұсқаны таңда.', tip: 'Сөйлемді толық оқып, оның нақты өмірдегі жағдайын елестет.' },
};
