import type { CourseLevel } from './courseData';
import type { ReadingQuestion, ReadingText } from './readingData';

type Seed = { title:string; text:string; facts:[string,string,string,string,string] };

const seeds: Record<CourseLevel, Seed[]> = {
  A1:[
    {title:'The welcome club',text:'Mira is a new student at West School. On Monday morning, she joins the welcome club in room twelve. She wants to practise greetings in English. Mira introduces herself to three students, and they invite her to sit with them at lunch.',facts:['Mira joining a welcome club','Room twelve','Monday morning','To practise English greetings','She makes three new friends']},
    {title:'My cousin Leo',text:'Leo lives with his parents and baby sister in a small house in Astana. Every Friday evening, he calls his cousin online. He wants the family to stay close. They show photos, talk about school and choose a film to watch together.',facts:['Leo and his family','A small house in Astana','Every Friday evening','To keep the family close','They choose a film together']},
    {title:'A busy school day',text:'Amina gets up at seven and walks to Central School. Her classes start at eight thirty. She follows a timetable because she does not want to be late. After four lessons, she has lunch and finishes the day with basketball practice.',facts:['Amina’s school routine','Central School','Classes start at eight thirty','She does not want to be late','She ends with basketball practice']},
    {title:'A new park',text:'There is a new park opposite Ben’s apartment. On Saturday afternoon, Ben explores it with his brother. They go because the old playground was too small. The park has a sports field, a café and a quiet reading area.',facts:['Ben exploring a new park','Opposite Ben’s apartment','Saturday afternoon','The old playground was too small','They find several activity areas']},
    {title:'Shopping for dinner',text:'Sara visits the Green Market after school on Tuesday. She needs food for a family dinner. She buys some rice, two tomatoes and a bottle of milk, but there is not any bread. Finally, she gets bread from the shop next door.',facts:['Sara shopping for dinner','The Green Market','Tuesday after school','Her family needs dinner ingredients','She finds bread next door']},
    {title:'Rainy-day hobbies',text:'Tom and Aya are staying at home because it is raining this afternoon. Tom is drawing a comic while Aya is learning a song. They want to enjoy their free time without screens. At the end, they perform the song and show the comic to their parents.',facts:['Tom and Aya enjoying hobbies','At home','A rainy afternoon','They want time without screens','They share their work with their parents']},
    {title:'The lost backpack',text:'Yesterday, Dani left his backpack on a bus near the city library. He returned to the station because his homework was inside. A driver found the bag under a seat and called the school. Dani got everything back before dinner.',facts:['Dani’s lost backpack','Near the city library','Yesterday','His homework was inside','A driver returned the bag']},
  ],
  A2:[
    {title:'The community kitchen',text:'Nora volunteers at a community kitchen in the city centre every second Saturday. The kitchen prepares meals for older residents. Nora joined because she wanted to do useful local work. This month, the team has served two hundred meals and has invited new volunteers.',facts:['A community kitchen project','The city centre','Every second Saturday','Nora wanted useful local work','The team served two hundred meals']},
    {title:'A different working week',text:'Karim usually studies at the library, but this week he is preparing for an exam at home. The library is being repaired until Friday. He chose the kitchen table because it has better light. He has discovered that short breaks help him concentrate.',facts:['Karim changing his study routine','At home','This week','The library is being repaired','Short breaks improve his focus']},
    {title:'The storm during the trip',text:'While Eva and her classmates were walking through a nature reserve, a storm began. They were carrying waterproof jackets because their guide had checked the forecast. The group waited in a visitor centre until the rain stopped, so everyone returned safely.',facts:['A class trip during a storm','A nature reserve','During a class walk','The guide had checked the forecast','The group returned safely']},
    {title:'A first public performance',text:'Ilya has played the guitar for three years, but he performed in public for the first time last weekend. He entered a school concert because his teacher encouraged him. Although he felt nervous at first, the audience’s reaction made him want to perform again.',facts:['Ilya’s first public performance','A school concert','Last weekend','His teacher encouraged him','He wants to perform again']},
    {title:'Planning a greener journey',text:'Next month, Lina’s family is going to travel from Almaty to Tashkent. They are taking a train instead of flying because they want a lower-carbon journey. Lina has already booked the seats and will prepare food on Friday. They expect the trip to take about sixteen hours.',facts:['A family train journey','From Almaty to Tashkent','Next month','They want a lower-carbon trip','The journey should take sixteen hours']},
    {title:'Rules for the science fair',text:'Students must submit their science-fair plans by Thursday, but they do not have to finish the projects yet. If a project uses electricity, a teacher will check it before the event. These rules exist to prevent accidents. As a result, every team can demonstrate its idea safely.',facts:['Science-fair safety rules','At a school event','Plans are due Thursday','The school wants to prevent accidents','Teams can demonstrate safely']},
    {title:'Two views of city life',text:'The school blog published two opinions about city life yesterday. Mei enjoys public transport and cultural events, whereas Sam prefers quieter neighbourhoods. The editor included both views because readers need a balanced comparison. The article ends by suggesting that no place suits everyone.',facts:['Different opinions about city life','A school blog','Yesterday','Readers need a balanced comparison','No place suits everyone']},
  ],
  B1:[
    {title:'The photograph that changed the plan',text:'Before the hiking group left, Yasmin had studied an old map of the valley. During the walk, she noticed that a bridge shown on the map had disappeared. Because she had photographed a newer route at the visitor centre, the group avoided a dangerous crossing and reached the campsite before dark.',facts:['A hiking group changing route','A mountain valley','Before dark','The old bridge had disappeared','The group reached camp safely']},
    {title:'Learning through a long project',text:'Noah has been building a small weather station since January. He has tested several sensors and has already replaced two unreliable parts. He began the project to understand how local forecasts are made. The station now sends data to his class, although he is still improving its accuracy.',facts:['Noah’s weather-station project','His school community','Since January','He wanted to understand forecasts','The station sends data to his class']},
    {title:'A factory becomes a library',text:'An abandoned factory has been transformed into a public library by local architects. Most original walls were preserved, while the machinery was reused as furniture. The building was saved because residents opposed its demolition. It is now visited by more than a thousand people each week.',facts:['A factory converted into a library','An abandoned factory building','Each week','Residents opposed demolition','Over a thousand people visit']},
    {title:'What the coach actually said',text:'After the final match, several websites reported that the coach had blamed the goalkeeper. She later explained that she had praised the whole team and had only asked the players to communicate more clearly. The club released the complete interview so supporters could judge her comments in context.',facts:['A coach’s comments being misreported','After a final match','Later that day','Websites removed the context','The club published the full interview']},
    {title:'The neighbour who started a garden',text:'Mr Adil, who had worked as a biology teacher, turned an empty piece of land into a community garden. The families that live nearby now grow vegetables there. He created the project because children had few opportunities to learn outdoors. The garden has also become a meeting place.',facts:['A community garden project','An empty local plot','After Mr Adil retired','Children needed outdoor learning','The garden became a meeting place']},
    {title:'A decision I would change',text:'Last summer, Kim refused a place on an exchange programme because she was worried about travelling alone. If she had spoken to former participants, she would have understood how much support was available. She now attends online language exchanges and would accept a similar opportunity in future.',facts:['Kim reconsidering an exchange','An international programme','Last summer','She feared travelling alone','She would accept next time']},
    {title:'Should homework be redesigned?',text:'A student newspaper surveyed three hundred learners about homework. Most did not want it removed, but they preferred fewer repetitive exercises and more practical projects. The writers argue that quantity alone does not improve learning. They recommend tasks that require research, choice and reflection.',facts:['A survey about homework','A student newspaper','During the current term','Students wanted more useful tasks','The writers recommend practical projects']},
  ],
  B2:[
    {title:'Forecasting beyond the deadline',text:'By the time the coastal barrier is completed in 2032, engineers will have worked on it for almost a decade. Supporters claim it will have protected thousands of homes, whereas critics question whether sea levels will have risen faster than predicted. The debate shows why long-term planning must account for uncertainty rather than rely on a single forecast.',facts:['Uncertainty in coastal planning','A coastal barrier project','By 2032','Sea-level forecasts may change','Plans should account for uncertainty']},
    {title:'When restoration is outsourced',text:'The theatre had its roof restored by a specialist firm after water damage was discovered. Although the work was expected to finish in June, several historical details had been removed without permission. The council has now had them recreated. The case demonstrates that outsourcing responsibility does not remove the need for expert supervision.',facts:['Problems during theatre restoration','A historical theatre','After water damage','Work lacked expert supervision','Removed details were recreated']},
    {title:'A quotation without its context',text:'The researcher was reported as saying that online learning had failed. In fact, she had argued that it was ineffective only when students received no feedback. Once the full lecture was published, the simplified quotation was widely corrected. The incident illustrates how reported speech can distort a carefully qualified claim.',facts:['A researcher being misquoted','An online-learning lecture','After the full lecture appeared','A qualification was omitted','The misleading quote was corrected']},
    {title:'Had the river been ignored',text:'Had residents not documented the pollution, the factory might have continued releasing waste for years. The authorities acted only after independent samples had been published. If monitoring were more transparent now, public trust would be stronger. The case links a past failure of oversight with a continuing political consequence.',facts:['Residents exposing river pollution','A river near a factory','After samples were published','Official monitoring had failed','Authorities stopped the pollution']},
    {title:'What might have caused the outage?',text:'The network outage cannot have been caused by demand alone because traffic was below average. Engineers believe an update may have damaged a configuration file, while managers admit it should have been tested more carefully. The final report must have considered several explanations before identifying responsibility.',facts:['Possible causes of a network outage','A digital network','During a low-traffic period','An update may have damaged a file','Testing procedures were questioned']},
    {title:'Remembering to question a claim',text:'People often remember reading a dramatic headline but forget to check its source. Stopping to examine the evidence can prevent false information from spreading, whereas stopping checking altogether makes manipulation easier. Media educators suggest comparing several reports and looking for the original data before sharing a claim.',facts:['Checking claims before sharing','Online news reports','Before sharing information','Headlines can be misleading','Readers should compare sources']},
    {title:'Rarely is complexity persuasive',text:'Rarely does an argument become stronger merely because it uses longer sentences. A well-structured essay, supported by precise evidence, is usually more convincing than one filled with unnecessary terminology. Having drafted a paragraph, a writer should therefore check whether every connector clarifies the logic rather than simply making the style appear formal.',facts:['Clarity in persuasive writing','A structured academic essay','After drafting a paragraph','Complexity can hide weak logic','Writers should check every connector']},
  ],
};

const prompts = ['What is the text mainly about?','Where does the situation take place?','When does it happen?','Why does the main situation occur?','What is the result or conclusion?'];

export function getExpandedReading(level:CourseLevel, lessonIndex:number): ReadingText[] {
  const seed = seeds[level][lessonIndex];
  const questions: ReadingQuestion[] = seed.facts.map((correct, factIndex) => {
    const alternatives = seeds[level].map((item) => item.facts[factIndex]).filter((item) => item !== correct).slice(lessonIndex % 3, lessonIndex % 3 + 3);
    const options = [correct, ...alternatives];
    const shift = (lessonIndex + factIndex) % options.length;
    return { prompt:prompts[factIndex], options:[...options.slice(shift), ...options.slice(0, shift)], correct };
  });
  return [{ title:seed.title, text:seed.text, questions }];
}
