import type { CourseLevel } from './courseData';
import type { UnitExercise } from './unitExercises';

type Example = [prompt:string, answer:string];

const examples: Record<CourseLevel, Example[][]> = {
  A1: [
    [['I ___ fifteen years old.','am'],['My sister ___ at school.','is'],['We ___ from Kazakhstan.','are'],['You ___ my new classmate.','are'],['It ___ a beautiful day.','is'],['They ___ in the classroom.','are'],['My name ___ Amina.','is'],['I ___ ready for the lesson.','am'],['Tom and Ben ___ friends.','are'],['The book ___ on the desk.','is']],
    [['I ___ got a blue backpack.','have'],['She ___ got two brothers.','has'],['We ___ got a new teacher.','have'],['Ali ___ got a football.','has'],['They ___ got a small dog.','have'],['My mother ___ got a car.','has'],['You ___ got a good idea.','have'],['The house ___ got three rooms.','has'],['I ___ got an English dictionary.','have'],['Dana and Sara ___ got bicycles.','have']],
    [['I ___ breakfast at seven.','eat'],['She ___ to school by bus.','goes'],['We ___ English every Monday.','study'],['My father ___ coffee in the morning.','drinks'],['They ___ football after school.','play'],['He ___ his homework at six.','does'],['I ___ my room on Saturday.','clean'],['Aruzhan ___ books before bed.','reads'],['You ___ very fast.','run'],['The shop ___ at nine.','opens']],
    [['There ___ a sofa in the living room.','is'],['There ___ four chairs in the kitchen.','are'],['The bank is ___ the café and the shop.','between'],['The keys are ___ the table.','on'],['There ___ a park near my house.','is'],['The cat is ___ the chair.','under'],['There ___ two windows in my room.','are'],['The school is ___ the library.','opposite'],['The books are ___ the bag.','in'],['There ___ not a hospital here.','is']],
    [['I would like ___ orange.','an'],['We have ___ bread at home.','some'],['Is there ___ milk in the fridge?','any'],['She buys two ___ of water.','bottles'],['There are ___ apples in the basket.','some'],['I do not have ___ money.','any'],['This T-shirt is too ___.','expensive'],['Can I have a ___ of tea?','cup'],['How ___ is this jacket?','much'],['My favourite food ___ pasta.','is']],
    [['I ___ doing my homework now.','am'],['She is ___ to music.','listening'],['They ___ playing basketball outside.','are'],['We are ___ dinner at the moment.','cooking'],['He ___ wearing a blue jacket.','is'],['The baby is ___.','sleeping'],['I am not ___ television.','watching'],['___ you reading this book?','Are'],['My friends are ___ in the park.','running'],['It is ___ today.','raining']],
    [['I ___ my grandmother yesterday.','visited'],['We ___ to the cinema last Saturday.','went'],['She ___ a funny story.','told'],['They ___ football after school.','played'],['He did not ___ breakfast.','eat'],['___ you see the new student?','Did'],['My family ___ in Almaty in 2024.','lived'],['I ___ a beautiful bird in the park.','saw'],['Dana ___ her homework early.','finished'],['The lesson ___ at ten o’clock.','started']],
  ],
  A2: [
    [['I saw ___ exciting match yesterday.','an'],['___ moon looks bright tonight.','The'],['She wants to become ___ doctor.','a'],['We visited ___ United Kingdom last year.','the'],['My father goes to ___ work at eight.','—'],['This is ___ book you gave me.','the'],['They live near ___ river.','a'],['___ Mount Everest is very high.','—'],['He plays ___ guitar well.','the'],['I need ___ umbrella today.','an']],
    [['Sara usually ___ from home.','works'],['Listen! Someone is ___ at the door.','knocking'],['I ___ this jacket every winter.','wear'],['We are ___ for the test this week.','studying'],['He never ___ breakfast.','skips'],['Why are you ___ so fast?','walking'],['My train ___ at seven every morning.','leaves'],['The children are ___ quietly now.','reading'],['I often ___ my cousins.','visit'],['She is not ___ today.','working']],
    [['I was ___ when the phone rang.','sleeping'],['They ___ home when it started to snow.','were walking'],['While I was cooking, my sister ___ the table.','was setting'],['The bus ___ while we were waiting.','arrived'],['What were you ___ at eight?','doing'],['He fell while he was ___.','running'],['We were watching a film when the lights ___ out.','went'],['She ___ her key while she was shopping.','lost'],['It was raining when I ___ the house.','left'],['The students were writing while the teacher ___.','was speaking']],
    [['I have never ___ sushi.','tried'],['We ___ Paris last summer.','visited'],['She has ___ finished her project.','just'],['Did you call him ___?','yesterday'],['He has lived here ___ five years.','for'],['They have known each other ___ 2020.','since'],['I ___ that film two days ago.','saw'],['Have you ever ___ a horse?','ridden'],['My brother has not arrived ___.','yet'],['We have already ___ our tickets.','bought']],
    [['I think our team ___ win.','will'],['She is going to ___ medicine.','study'],['We are ___ our teacher at four.','meeting'],['Look at those clouds! It is going to ___.','rain'],['I ___ help you with that bag.','will'],['They are going to ___ a new house.','buy'],['The lesson ___ at nine tomorrow.','starts'],['What are you ___ this evening?','doing'],['I think people will ___ longer in the future.','live'],['He is not going to ___ the invitation.','accept']],
    [['You ___ show your passport at the airport.','must'],['You ___ eat more vegetables.','should'],['We ___ finish today; tomorrow is fine.','do not have to'],['If you heat ice, it ___.','melts'],['If I have time, I ___ call you.','will'],['Students ___ use phones during the exam.','must not'],['It ___ rain later, so take an umbrella.','might'],['If she studies, she ___ pass.','will'],['___ you help me, please?','Could'],['You ___ see a doctor if you feel ill.','should']],
    [['I was tired, ___ I continued working.','but'],['___ it was raining, we went for a walk.','Although'],['First, chop the onions. ___, heat the oil.','Then'],['She stayed home ___ she was ill.','because'],['The room is small; ___, it is comfortable.','however'],['We missed the bus, ___ we took a taxi.','so'],['___, I would like to explain the problem.','First'],['He is friendly ___ helpful.','and'],['I enjoy cities, ___ my sister prefers villages.','whereas'],['Finally, we ___ home safely.','arrived']],
  ],
  B1: [
    [['We booked ___ room near the station.','a'],['___ advice you gave me was helpful.','The'],['She studies at ___ university in Astana.','a'],['I had ___ breakfast before leaving.','—'],['They crossed ___ Pacific Ocean.','the'],['He is ___ honest person.','an'],['We visited ___ Netherlands in spring.','the'],['___ life can be unpredictable.','—'],['This is ___ best solution.','the'],['She plays ___ chess every weekend.','—']],
    [['By noon, I had ___ the report.','finished'],['She has ___ three emails today.','written'],['They had left before we ___.','arrived'],['I have not seen him ___ Monday.','since'],['He was nervous because he had not ___.','prepared'],['Have you ___ your decision yet?','made'],['The film had already ___ when we entered.','started'],['We ___ this problem last week.','discussed'],['She has worked here ___ six months.','for'],['After I had eaten, I ___ better.','felt']],
    [['I have been ___ for an hour.','waiting'],['She has been ___ English since January.','learning'],['How long have they been ___ here?','living'],['It has been ___ all day.','snowing'],['He is tired because he has been ___.','running'],['We have been ___ on this project for weeks.','working'],['My eyes hurt because I have been ___.','reading'],['Has she been ___ enough water?','drinking'],['They have not been ___ attention.','paying'],['The dog has been ___ since midnight.','barking']],
    [['If I had more money, I ___ travel.','would'],['She would help if she ___ time.','had'],['What would you do if you ___ famous?','were'],['If we lived closer, we ___ meet often.','would'],['He would buy it if it ___ cheaper.','were'],['If I ___ you, I would apologise.','were'],['They would learn faster if they ___ daily.','practised'],['If she knew the answer, she ___ tell us.','would'],['Where would you live if you ___ choose?','could'],['I would not worry if I ___ him.','trusted']],
    [['If I had studied, I would have ___.','passed'],['She would have come if you had ___ her.','invited'],['If we had left earlier, we ___ have caught the train.','would'],['They would not have lost if they had ___.','practised'],['Had I known, I would have ___ you.','called'],['If he had listened, he would not have made the ___.','mistake'],['What would you have done if you had ___ it?','seen'],['If it had not rained, we would have ___ outside.','eaten'],['She would have succeeded if she had ___.','tried'],['If I had remembered, I would have ___ a gift.','bought']],
    [['If I had slept earlier, I would not ___ tired now.','be'],['If she were organised, she would have ___ on time.','arrived'],['If they had accepted the offer, they would ___ abroad now.','live'],['I would speak French if I had ___ it at school.','studied'],['If he were kinder, he would not have ___ that.','said'],['If we had saved money, we could ___ a car now.','buy'],['She would be confident if she had ___ more.','practised'],['If I liked cold weather, I would have ___ north.','moved'],['He would know the answer if he had ___ the book.','read'],['If they had taken the map, they would not ___ lost now.','be']],
    [['This time tomorrow, I will be ___.','flying'],['At eight, she will be ___ dinner.','cooking'],['The man ___ near the door is my uncle.','standing'],['The book, ___ won an award, is excellent.','which'],['I enjoy ___ articles in English.','reading'],['By Friday, we will be ___ in a hotel.','staying'],['Students ___ want help can ask me.','who'],['She avoided ___ the question.','answering'],['Tomorrow morning, they will be ___.','travelling'],['The café ___ we met has closed.','where']],
  ],
  B2: [
    [['By 2030, they will have ___ the bridge.','completed'],['At noon, I will have been ___ for six hours.','working'],['This is the first time she has ___ abroad.','lived'],['By next month, we will have ___ enough money.','saved'],['He will have been ___ for twenty years.','teaching'],['I had been waiting before the bus ___.','arrived'],['She has ___ three proposals this week.','written'],['By then, the company will have ___ rapidly.','grown'],['They will have been ___ all night.','driving'],['Never before have I ___ such skill.','seen']],
    [['The results will be ___ tomorrow.','announced'],['The road is being ___ at the moment.','repaired'],['The letter had been ___ before noon.','sent'],['This painting was ___ by a local artist.','created'],['The problem must be ___ immediately.','solved'],['A new hospital is going to be ___.','built'],['The suspect is believed to have ___ abroad.','escaped'],['The documents have been ___.','signed'],['English is ___ in many countries.','spoken'],['The project should have been ___ earlier.','finished']],
    [['She said that she ___ busy.','was'],['He asked where I ___.','lived'],['They told us not to ___ late.','be'],['Maya said she had ___ the film.','seen'],['He asked whether I could ___ him.','help'],['The teacher said the test ___ be difficult.','would'],['She told me that she was ___.','leaving'],['I asked him what he ___.','wanted'],['They said they had arrived the day ___.','before'],['He advised me to ___ more.','practise']],
    [['You may leave provided that you ___ the work.','finish'],['Unless we hurry, we ___ miss the train.','will'],['Had I known, I would have ___ differently.','acted'],['As long as you follow the rules, you ___ join.','can'],['Were she here, she would ___ what to do.','know'],['If it had not been for you, I would have ___.','failed'],['Supposing you lost your phone, what would you ___?','do'],['Even if he apologised, she would not ___ him.','trust'],['Should you need help, please ___ me.','call'],['Only if we cooperate will we ___.','succeed']],
    [['He must have ___ the message.','forgotten'],['You should have ___ me earlier.','told'],['They cannot have ___ already.','left'],['She might have ___ the wrong train.','taken'],['We need not have ___ so much food.','bought'],['He could have ___ the competition.','won'],['You ought to have ___ more careful.','been'],['The lights are off; they must have ___ home.','gone'],['She may not have ___ the email.','received'],['I would have ___ you, but I was busy.','helped']],
    [['I remember ___ her before.','meeting'],['He stopped to ___ some water.','buy'],['Try ___ the computer.','restarting'],['She regrets ___ the secret.','sharing'],['We agreed to ___ after lunch.','meet'],['I cannot afford to ___ that car.','buy'],['He denied ___ the window.','breaking'],['Remember to ___ the door.','lock'],['They suggested ___ by train.','travelling'],['She went on to ___ the next topic.','explain']],
    [['Rarely have I ___ such courage.','seen'],['The people ___ outside are reporters.','waiting'],['Despite ___ tired, she continued.','being'],['Not only did he apologise, but he also ___ the damage.','repaired'],['The proposal, ___ carefully, could work.','implemented'],['No sooner had we arrived than it ___ raining.','started'],['Whereas one plan is cheap, the other is more ___.','reliable'],['Under no circumstances should you ___ this file.','delete'],['Having ___ the report, she sent it.','finished'],['Nevertheless, the team ___ to continue.','decided']],
  ],
};

export function getWrittenExamples(level: CourseLevel, lessonIndex: number): UnitExercise[] {
  return examples[level][lessonIndex].map(([prompt, answer]) => ({
    kind:'write', prompt:`Type the missing word: ${prompt}`,
    correct:answer, model:prompt.replace('___', answer),
  }));
}
